name: SimpleTips
main: com.keithlawless.plugins.SimpleTips.SimpleTips
version: 1.2

commands:
    tip:
        description: Display and edit SimpleTips if you have permission.
        usage: |
            Here's how to use the 'tip' command...
            /tip                        To see a random tip
            /tip list                   To see a list of all tips
            /tip add [text]             To add a tip to the list
            /tip del [num]              To delete a tip
            /tip replace [num] [text]   To replace a tip with new text

permissions:
    tip.*:
        description: Grant access to all tip commands.
        children:
            tip.list: true
            tip.add: true
            tip.del: true
            tip.replace: true
    tip.list:
        description: List the tips for this server.
    tip.add:
        description: Add a tip to the server.
    tip.del:
        description: Delete a tip from the server.
    tip.replace:
        description: Replace a tip with another message (ie. Edit a tip.)

